<?php
    require_once 'mail.php';
$taxis = array(
    array('username' => 'GE2842', 'first_name' => 'Bakil', 'last_name' => 'ACIK', 'email' => 'baqil@icloud.com'),
    array('username' => 'GE2640', 'first_name' => 'Carlos', 'last_name' => 'GAGO', 'email' => 'allo.taxi@me.com'),
    array('username' => 'GE2726', 'first_name' => 'Hicham', 'last_name' => 'TAZI', 'email' => 'thichame@hotmail.com'),
    array('username' => 'GE2702', 'first_name' => 'Burim', 'last_name' => 'MUSTAFA', 'email' => 'burimmustafa81@gmail.com'),
    array('username' => 'GE2738', 'first_name' => 'Khalil', 'last_name' => 'BELMEJDOUB', 'email' => 'khalilbelmejdoub@icloud.com'),
    array('username' => 'GE2634', 'first_name' => 'Rabah', 'last_name' => 'BENHAOUES', 'email' => 'rabahnadir@hotmail.com'),
    array('username' => 'GE2568', 'first_name' => 'Mourad', 'last_name' => 'JERFEL', 'email' => 'm.jerfel@gmail.com'),
    array('username' => 'GE2843', 'first_name' => 'Sylvain', 'last_name' => 'LEVI', 'email' => 'levidan731@gmail.com'),
    array('username' => 'GE2584', 'first_name' => 'Med', 'last_name' => 'LABIAD', 'email' => 'lab135@hotmail.com'),
    array('username' => 'GE2735', 'first_name' => 'Chems', 'last_name' => 'GUELLAI', 'email' => 'chems@bluewin.ch'),
    array('username' => 'GE2745', 'first_name' => 'Zoubir', 'last_name' => 'BOULAC', 'email' => 'blzfzoubair@hotmail.fr'),
    array('username' => 'GE2762', 'first_name' => 'Raymond', 'last_name' => 'JULIAN', 'email' => 'raymond.julian@cegetel.net'),
    array('username' => 'GE2816', 'first_name' => 'Omar', 'last_name' => 'TAHA', 'email' => 'walass@bluewin.ch'),
    array('username' => 'GE600', 'first_name' => 'Humberto', 'last_name' => 'RODRIGUES', 'email' => 'meles600@hotmail.com'),
    array('username' => 'GE654', 'first_name' => 'Lionel', 'last_name' => 'ALBINO', 'email' => 'la76@hotmail.ch'),
    array('username' => 'GE458', 'first_name' => 'Costa', 'last_name' => 'VENANCIO', 'email' => 'venancio-costa@hotmail.com'),
    array('username' => 'GE665', 'first_name' => 'Georges', 'last_name' => 'FLORES', 'email' => 'floresg1805@yahoo.fr'),
    array('username' => 'GE857', 'first_name' => 'Jose Manuel', 'last_name' => 'GRILLE FERREIRO', 'email' => 'jose.grille@hotmail.com'),
    array('username' => 'GE762', 'first_name' => 'Jose', 'last_name' => 'GONCALVES', 'email' => 'jossboss@bluewin.ch'),
    array('username' => 'GE9', 'first_name' => 'Hernani', 'last_name' => 'PIRES DE OLIVEIRA', 'email' => 'kaon09@hotmail.com'),
    array('username' => 'GE101', 'first_name' => 'José', 'last_name' => 'NUNES', 'email' => 'taxijo101@hotmail.com'),
    array('username' => 'GE501', 'first_name' => 'Fernando', 'last_name' => 'RODRIGUES', 'email' => 'fernando@treze.pt'),
    array('username' => 'GE321', 'first_name' => 'Rui', 'last_name' => 'DA COSTA', 'email' => 'ruidacosta3@gmail.com'),
    array('username' => 'GE378', 'first_name' => 'Joaquim', 'last_name' => 'GOMES', 'email' => 'quimgomes76@gmail.com'),
    array('username' => 'GE1349', 'first_name' => 'José', 'last_name' => 'GONÇALVES', 'email' => 'info@taxigeneve.ch'),
    array('username' => 'GE1300', 'first_name' => 'Johnny', 'last_name' => 'SCHOENENBERGER', 'email' => 'js@taxidriver.ch'),
    array('username' => 'GE73', 'first_name' => 'Antonio', 'last_name' => 'MARQUES', 'email' => 'antonio_mortagua@hotmail.com'),
    array('username' => 'GE893', 'first_name' => 'Arlindo', 'last_name' => 'DA FONSECA', 'email' => 'taxifonseca@hotmail.com'),
    array('username' => 'GE1117', 'first_name' => 'Antonio', 'last_name' => 'COELHO', 'email' => 'antoniocoelho1117@gmail.com'),
    array('username' => 'GE301', 'first_name' => 'Antonio', 'last_name' => 'MESTRE', 'email' => 'mestre.anto@gmail.com'),
    array('username' => 'GE328', 'first_name' => 'Antonio', 'last_name' => 'BONITO', 'email' => 'taxibonito@gmail.com'),
    array('username' => 'GE814', 'first_name' => 'Ridha', 'last_name' => 'EL AHMEDI', 'email' => 'elahmedi814@gmail.com'),
    array('username' => 'GE347', 'first_name' => 'Pascale', 'last_name' => 'RECHIGNAC', 'email' => 'parec37@aol.com'),
    array('username' => 'GE702', 'first_name' => 'Pedro', 'last_name' => 'GOMES', 'email' => 'pedrotaxi702@hotmail.com'),
    array('username' => 'GE71', 'first_name' => 'Jorge', 'last_name' => 'TRINDADE', 'email' => 'jatrindade@hotmail.fr'),
    array('username' => 'GE263', 'first_name' => 'Domingos', 'last_name' => 'ROCHA', 'email' => 'flaviorochago@gmail.com'),
    array('username' => 'GE65', 'first_name' => 'Carlos', 'last_name' => 'DE FREITAS', 'email' => 'carlosge65@gmail.com'),
    array('username' => 'GE364', 'first_name' => 'José', 'last_name' => 'GUERREIRO', 'email' => 'jose-guerreiro@hotmail.com'),
    array('username' => 'GE595', 'first_name' => 'Fabio', 'last_name' => 'MOTA', 'email' => 'ge595taxi@gmail.com'),
    array('username' => 'GE867', 'first_name' => 'Rui', 'last_name' => 'GUEDES', 'email' => 'rmpguedes@hotmail.com'),
    array('username' => 'GE195', 'first_name' => 'Jose Fernando', 'last_name' => 'DE ANDRADE SANTOS', 'email' => 'andrade.couto@hotmail.com'),
    array('username' => 'GE1341', 'first_name' => 'Hassan', 'last_name' => 'BARAKA', 'email' => 'hassanb@bluewin.ch'),
    array('username' => 'GE845', 'first_name' => 'Moncef', 'last_name' => 'SAIDANI', 'email' => 'moncefsaidani@hotmail.com'),
    array('username' => 'GE1203', 'first_name' => 'Victor', 'last_name' => 'FRANCISCO', 'email' => 'info@gotaxi.ch'),
    array('username' => 'GE172', 'first_name' => 'Manuel', 'last_name' => 'SILVARES DA SILVA', 'email' => 'silvares63@gmail.com'),
    array('username' => 'GE1156', 'first_name' => 'Fatana', 'last_name' => 'JOSE', 'email' => 'fatanajose@gmail.com'),
    array('username' => 'GE238', 'first_name' => 'Miguel', 'last_name' => 'BARROS', 'email' => 'mda.barros@gmail.com'),
    array('username' => 'GE90', 'first_name' => 'Luis', 'last_name' => 'CRUZ', 'email' => 'taxicruzgeneve@gmail.com'),
    array('username' => 'GE1303', 'first_name' => 'Joaquim', 'last_name' => 'FERNANDES', 'email' => 'fernandes1303@hotmail.ch'),
    array('username' => 'GE1387', 'first_name' => 'Nelio', 'last_name' => 'CABACO', 'email' => 'nelioramoscabaco@msn.com'),
    array('username' => 'GE1442', 'first_name' => 'Luis', 'last_name' => 'FERRAZ', 'email' => 'slbenferraz@hotmail.com'),
    array('username' => 'GE1258', 'first_name' => 'Jose', 'last_name' => 'MESQUITA', 'email' => 'info@gotaxi.ch'),
    array('username' => 'GE621', 'first_name' => 'Paulo', 'last_name' => 'OCHOA', 'email' => 'deltaochoa@netscape.net'),
    array('username' => 'GE39', 'first_name' => 'Paulo', 'last_name' => 'LOPES MESQUITA', 'email' => 'taximesquita@hotmail.com'),
    array('username' => 'GE544', 'first_name' => 'Manuel', 'last_name' => 'DE JESUS FERRAZ', 'email' => 'dejesusferraz@hotmail.com'),
    array('username' => 'GE237', 'first_name' => 'Mohamed', 'last_name' => 'MOUNAIM', 'email' => 'moha.mounaim@gmail.com'),
    array('username' => 'GE48', 'first_name' => 'Abdelhamid', 'last_name' => 'TEBISSI', 'email' => 'tebissi2009@hotmail.com'),
    array('username' => 'GE522', 'first_name' => 'Dario', 'last_name' => 'SANCHEZ', 'email' => 'dar07@gmail.com'),
    array('username' => 'GE87', 'first_name' => 'Antonio', 'last_name' => 'RANA', 'email' => 'antonioranao@hotmail.com'),
    array('username' => 'GE282', 'first_name' => 'José', 'last_name' => 'GONCALVES', 'email' => 'gmj67@msn.com'),
    array('username' => 'GE808', 'first_name' => 'Manuel', 'last_name' => 'LOIS', 'email' => 'manuel.lois.808@gmail.com'),
    array('username' => 'GE1296', 'first_name' => 'Olivier', 'last_name' => 'VANNOD', 'email' => 'olivier.1296@hotmail.fr'),
    array('username' => 'GE205', 'first_name' => 'Jesus', 'last_name' => 'RUBIO-LOPEZ', 'email' => 'rubiolopez@me.com'),
    array('username' => 'GE1149', 'first_name' => 'Luciano', 'last_name' => 'ZAMBRELLA', 'email' => 'zambrella@bluewin.ch'),
    array('username' => 'GE397', 'first_name' => 'Carlos', 'last_name' => 'SABINA', 'email' => 'csabina12@gmail.com'),
    array('username' => 'GE812', 'first_name' => 'Nedsad', 'last_name' => 'MAHMULJIN', 'email' => 'mahmuljinn@hotmail.com'),
    array('username' => 'GE83', 'first_name' => 'Carlos Manuel', 'last_name' => 'DOS SANTOS MARQUES', 'email' => 'carlos.c.s@bluewin.ch'),
    array('username' => 'GE885', 'first_name' => 'Nelson', 'last_name' => 'OLIVEIRA LOPES', 'email' => 'oliveiranelson@icloud.com'),
    array('username' => 'GE765', 'first_name' => 'Carlos', 'last_name' => 'BEN', 'email' => 'cben@bluewin.ch'),
    array('username' => 'GE1283', 'first_name' => 'Carlos', 'last_name' => 'ALBINO', 'email' => 'carlos-albino@bluewin.ch'),
    array('username' => 'GE1418', 'first_name' => 'Jorge', 'last_name' => 'PINTO', 'email' => 'taxijorge@hotmail.fr'),
    array('username' => 'GE445', 'first_name' => 'Lucia', 'last_name' => 'GONÇALVES', 'email' => 'contact@snowcabgeneva.ch'),
    array('username' => 'GE567', 'first_name' => 'Paulo', 'last_name' => 'BENTO', 'email' => 'paulogeneve@hotmail.com'),
    array('username' => 'GE571', 'first_name' => 'Antonio', 'last_name' => 'FERNANDES', 'email' => 'antonio.fernandes10@bluewin.ch'),
    array('username' => 'GE429', 'first_name' => 'Jose', 'last_name' => 'OLIVEIRA', 'email' => 'oliveirajose65@hotmail.com'),
    array('username' => 'GE66', 'first_name' => 'Luis', 'last_name' => 'GOMES PESQUEIRA', 'email' => 'lai.pesqueira@hotmail.com'),
    array('username' => 'GE860', 'first_name' => 'Yared', 'last_name' => 'AREFAINE', 'email' => 'arefaineyared@yahoo.com'),
    array('username' => 'GE689', 'first_name' => 'Jose', 'last_name' => 'DE OLIVEIRA', 'email' => 'oliveirajose06@gmail.com'),
    array('username' => 'GE1370', 'first_name' => 'Paulo', 'last_name' => 'MELANCIA', 'email' => 'alexsporting-25@hotmail.com'),
    array('username' => 'GE1247', 'first_name' => 'Luis', 'last_name' => 'FERREIRA', 'email' => 'antonio.laia@hotmail.com'),
    array('username' => 'GE336', 'first_name' => 'Marc', 'last_name' => 'LOPEZ', 'email' => 'marclopez64336@gmail.com'),
    array('username' => 'GE1362', 'first_name' => 'Denis', 'last_name' => 'JACQUIER', 'email' => 'denis.jacquier555@gmail.com'),
    array('username' => 'GE57', 'first_name' => 'Carlos', 'last_name' => 'ALVAREZ', 'email' => 'caradino@orange.fr'),
    array('username' => 'GE126', 'first_name' => 'Jose Fernando', 'last_name' => 'DE ANDRADE SANTOS', 'email' => 'andrade.couto@hotmail.com'),
    array('username' => 'GE119', 'first_name' => 'Anibal', 'last_name' => 'ANTUNES', 'email' => 'anibaltaxi@hotmail.com'),
    array('username' => 'GE1134', 'first_name' => 'Jose', 'last_name' => 'DE SOUSA', 'email' => 'jose-sousa@windowslive.com'),
    array('username' => 'GE379', 'first_name' => 'Carlos', 'last_name' => 'ROSA', 'email' => 'rosa.379@windowslive.com'),
    array('username' => 'GE933', 'first_name' => 'Horacio', 'last_name' => 'MARTINS', 'email' => 'taxige933@gmail.com'),
    array('username' => 'GE70', 'first_name' => 'Fernando', 'last_name' => 'ANTONIO DA SILVA', 'email' => 'taxisilva@aol.com'),
    array('username' => 'GE1401', 'first_name' => 'Jean Paul', 'last_name' => 'PASQUIER', 'email' => 'jppasquier@hotmail.com'),
    array('username' => 'GE1440', 'first_name' => 'Alvaro', 'last_name' => 'TEIXEIRA', 'email' => 'alvarocteixeira2@gmail.com'),
    array('username' => 'GE1313', 'first_name' => 'Francesco', 'last_name' => 'RIZZO', 'email' => 'franci98@hotmail.com'),
    array('username' => 'GE1056', 'first_name' => 'Joseph', 'last_name' => 'DOCHE', 'email' => 'josephdoche@yahoo.fr'),
    array('username' => 'VD199346', 'first_name' => 'Pierre-André', 'last_name' => 'GIACOMETTI', 'email' => 'pagiacometti@bluewin.ch'),
    array('username' => 'GE1366', 'first_name' => 'Mouad', 'last_name' => 'EL KASSIMI', 'email' => 'melkassimi@hotmail.com'),
    array('username' => 'GE424', 'first_name' => 'Iseni', 'last_name' => 'AFRIM', 'email' => 'iseni.afrim5@icloud.com'),
    array('username' => 'GE368', 'first_name' => 'Manuel', 'last_name' => 'DOS SANTOS', 'email' => 'dossantos.d@bluewin.ch'),
    array('username' => 'GE545', 'first_name' => 'Luis', 'last_name' => 'DOS SANTOS CARVALHO', 'email' => 'luiscarvalho962@hotmail.com'),
    array('username' => 'GE110', 'first_name' => 'Abdessamad', 'last_name' => 'OUTALEB', 'email' => 'outalebsamad1619@gmail.com'),
    array('username' => 'GE1099', 'first_name' => 'Jorge', 'last_name' => 'SOUSA MELANCIA', 'email' => 'rsjmelancia@hotmail.com'),
    array('username' => 'GE362', 'first_name' => 'Anselmo Dinis', 'last_name' => 'DOS SANTOS', 'email' => 'dossantos.d@hotmail.ch'),
    array('username' => 'GE574', 'first_name' => 'Carmine', 'last_name' => 'CAPO', 'email' => 'capocarmine8@gmail.com'),
    array('username' => 'GE801', 'first_name' => 'Christian', 'last_name' => 'MORET', 'email' => 'cricrideperly@gmail.com'),
    array('username' => 'GE839', 'first_name' => 'Jorge', 'last_name' => 'PINHAO', 'email' => 'pinhao839@gmail.com'),
    array('username' => 'GE396', 'first_name' => 'Izek', 'last_name' => 'SERMAXHAJ', 'email' => 'izek_1@hotmail.com'),
    array('username' => 'GE1074', 'first_name' => 'Paulo', 'last_name' => 'FERNANDES', 'email' => 'paulofernandes64@hotmail.com'),
    array('username' => 'GE1324', 'first_name' => 'Kadrush', 'last_name' => 'DERMAKU', 'email' => 'kadd13@hotmail.com'),
    array('username' => 'GE1338', 'first_name' => 'Urs', 'last_name' => 'SCHÖNI', 'email' => 'u.schoeni@icloud.com'),
    array('username' => 'GE1348', 'first_name' => 'Alberto', 'last_name' => 'PEDROSA', 'email' => 'alberto.pedrosa@hotmail.com'),
    array('username' => 'GE1072', 'first_name' => 'Julio', 'last_name' => 'DA SILVA', 'email' => 'juliodasilva@hotmail.ch'),
    array('username' => 'GE163', 'first_name' => 'Hamza', 'last_name' => 'ABDESSADAK', 'email' => 'abdessakak.h@gmail.com'),
    array('username' => 'GE414', 'first_name' => 'Nabil', 'last_name' => 'OUALADI', 'email' => 'oualadinabil1976@gmail.com'),
    array('username' => 'GE450', 'first_name' => 'Julio Manuel', 'last_name' => 'LOURENCO FELIX', 'email' => 'taxifelix69@gmail.com'),
    array('username' => 'GE825', 'first_name' => 'Tibor', 'last_name' => 'ROTH', 'email' => 'tiro54@bluewin.ch'),
    array('username' => 'GE1178', 'first_name' => 'Emmanuel', 'last_name' => 'NGOMA', 'email' => 'taxingoma@gmail.com'),
    array('username' => 'GE138', 'first_name' => 'Saidani', 'last_name' => 'RIDHA', 'email' => 'ridhageneve@gmail.com'),
    array('username' => 'VD164044', 'first_name' => 'Ricardo', 'last_name' => 'ALFEIRAO', 'email' => 'taxiricardo@hotmail.ch'),
    array('username' => 'VD106137', 'first_name' => 'Milan', 'last_name' => 'BURSAC', 'email' => 'dellmtaxi@gmail.com'),
    array('username' => 'VD280309', 'first_name' => 'Ricardo', 'last_name' => 'ALFEIRAO', 'email' => 'taxiricardo@hotmail.ch'),
    array('username' => 'VD294158', 'first_name' => 'Pierre', 'last_name' => 'TELESE', 'email' => 'fatypierre@gmail.com'),
    array('username' => 'VD255794', 'first_name' => 'Yohann Charles', 'last_name' => 'BENHAIM', 'email' => 'y.benhaim@hotmail.com'),
    array('username' => 'GE1067', 'first_name' => 'André', 'last_name' => 'BORNEMISZA', 'email' => 'andrasb@hotmail.ch'),
    array('username' => 'GE402', 'first_name' => 'Olivier', 'last_name' => 'CHABLOZ', 'email' => 'olivierchabloz@yahoo.fr'),
    array('username' => 'GE3', 'first_name' => 'Rosa', 'last_name' => 'NAHMIAS', 'email' => 'rosa.nahmias@live.fr'),
    array('username' => 'GE141', 'first_name' => 'Hedi', 'last_name' => 'ZAYANI', 'email' => 'hedi.zayani@gmail.com'),
    array('username' => 'GE1402', 'first_name' => 'Pelayo', 'last_name' => 'MONTE HEVIA', 'email' => 'pelayomh@outlook.com'),
    array('username' => 'GE1143', 'first_name' => 'Corinne', 'last_name' => 'ALKAAR', 'email' => 'corinne.frueh@gmail.com'),
    array('username' => 'VD293705', 'first_name' => 'David', 'last_name' => 'ALFONSO', 'email' => 'cdnens2@hotmail.com'),
    array('username' => 'VD498548', 'first_name' => 'Abdulamir', 'last_name' => 'ALASSFAR', 'email' => 'alassfar@hotmail.com'),
    array('username' => 'GE1253', 'first_name' => 'Manuel', 'last_name' => 'DA CUNHA', 'email' => 'cunha1253@live.fr'),
    array('username' => 'GE1423', 'first_name' => 'José', 'last_name' => 'GONCALVES', 'email' => 'goncalves1423@gmail.com'),
    array('username' => 'GE768', 'first_name' => 'Jean-Robert', 'last_name' => 'MEILI', 'email' => 'jsutile@gmail.com'),
    array('username' => 'GE846', 'first_name' => 'Jacinto', 'last_name' => 'MARCALO', 'email' => 'j.marcalo@bluewin.ch'),
    array('username' => 'GE67', 'first_name' => 'Jésus', 'last_name' => 'GARCIA', 'email' => 'manuel.l@bluewin.ch'),
    array('username' => 'GE653', 'first_name' => 'Valentin', 'last_name' => 'MENDES', 'email' => 'valentin54@outlook.com'),
    array('username' => 'GE821', 'first_name' => 'Francisco', 'last_name' => 'MENDES MARTINHO', 'email' => 'fr.martinho@bluewin.ch'),
    array('username' => 'GE1220', 'first_name' => 'Ahmed', 'last_name' => 'ELKHARDGY', 'email' => 'elkhardgy@gmail.com'),
    array('username' => 'GE41', 'first_name' => 'Nedeljko', 'last_name' => 'VLAJKOVIC', 'email' => 'nedtaxi@hotmail.com'),
    array('username' => 'VD253569', 'first_name' => 'Mihailo', 'last_name' => 'MINIC', 'email' => 'minic.mihailo@gmail.com'),
    array('username' => 'VD463849', 'first_name' => 'Joao', 'last_name' => 'BULAS', 'email' => 'joaobulas@hotmail.com'),
    array('username' => 'GE192', 'first_name' => 'Martinho', 'last_name' => 'SILVERIO', 'email' => 'msilverio84@gmail.com'),
    array('username' => 'GE1263', 'first_name' => 'Agostinho', 'last_name' => 'DE CARVALHO COUTO', 'email' => 'afccouto@hotmail.com'),
    array('username' => 'GE570', 'first_name' => 'Slimane', 'last_name' => 'TABOUBI', 'email' => 'slim90@bluewin.ch'),
    array('username' => 'GE705', 'first_name' => 'Mansour', 'last_name' => 'MARZOUGUI', 'email' => 'mansourmarzou@yastax.ch'),
    array('username' => 'GE28', 'first_name' => 'Alain', 'last_name' => 'TALEB', 'email' => 'taleb123000@gmail.com'),
    array('username' => 'GE273', 'first_name' => 'Jean-Marie', 'last_name' => 'PRADA', 'email' => 'jmp67@bluewin.ch'),
    array('username' => 'GE000', 'first_name' => 'Florian', 'last_name' => 'KOHLI', 'email' => 'florian@rond.ch'),
    array('username' => 'GE771', 'first_name' => 'Claudio', 'last_name' => 'VERRECCHIA', 'email' => 'stargates@hotmail.ch'),
    array('username' => 'GE322', 'first_name' => 'Fouad', 'last_name' => 'BENAGHMOUCH', 'email' => 'fouadb19@gmail.com'),
    array('username' => 'VD304846', 'first_name' => 'David', 'last_name' => 'VERISIMO', 'email' => 'swissindigo@gmail.com'),
    array('username' => 'GE817', 'first_name' => 'Jalel', 'last_name' => 'EL KHEDRI', 'email' => 'fjalel81@gmail.com'),
    array('username' => 'GE1411', 'first_name' => 'Imed', 'last_name' => 'FERCHICHI', 'email' => 'i.ferchichi@gmail.com'),
    array('username' => 'VD553237', 'first_name' => 'Hichem', 'last_name' => 'KHEMILA', 'email' => 'hichem_khemila@hotmail.com'),
    array('username' => 'GE1308', 'first_name' => 'Farjaoui', 'last_name' => 'LARBI', 'email' => 'larbirf@gmail.com'),
    array('username' => 'GE859', 'first_name' => 'Antonio', 'last_name' => 'MELO', 'email' => 'taximen56@gmail.com'),
    array('username' => 'GE564', 'first_name' => 'Belkheir', 'last_name' => 'BENAMAR', 'email' => 'belkheirbenamar@gmail.com'),
    array('username' => 'GE842', 'first_name' => 'José Manuel', 'last_name' => 'GUERREIRO', 'email' => 'marie.jo@hotmail.ch'),
    array('username' => 'GE146', 'first_name' => 'Jovo', 'last_name' => 'ADAMOVIC', 'email' => 'a.jovo1@gmail.com'),
    array('username' => 'GE528', 'first_name' => 'Youssef', 'last_name' => 'LMALKI', 'email' => 'youssef-lmalki@bluewin.ch'),
    array('username' => 'GE188', 'first_name' => 'Abdessamad', 'last_name' => 'HATRI', 'email' => 'hatriabdessamad.ge@gmail.com'),
    array('username' => 'GE295', 'first_name' => 'Ayaz', 'last_name' => 'AHMED', 'email' => 'ayaz7@hotmail.fr'),
    array('username' => 'GE18', 'first_name' => 'Hamdi', 'last_name' => 'BUCI', 'email' => 'fisnik.buci@master.hes-so.ch'),
    array('username' => 'GE853', 'first_name' => 'Mohamed', 'last_name' => 'CHRAIET', 'email' => 'koukou75@hotmail.ch'),
    array('username' => 'GE201', 'first_name' => 'Imed', 'last_name' => 'ASSEL', 'email' => 'jasmin2009@hotmail.ch'),
    array('username' => 'GE268', 'first_name' => 'Hamadi', 'last_name' => 'GUIZANI', 'email' => 'hamadi.guizani@hotmail.fr'),
    array('username' => 'GE165', 'first_name' => 'Nouri', 'last_name' => 'OUERHANI', 'email' => 'nouritaxi@gmail.com'),
    array('username' => 'GE265', 'first_name' => 'Jean', 'last_name' => 'RUIZ', 'email' => 'ruiz.jean58@gmail.com'),
    array('username' => 'GE829', 'first_name' => 'Mohammed', 'last_name' => 'ZDIHRI', 'email' => 'les-alpesimo@hotmail.com'),
    array('username' => 'GE1342', 'first_name' => 'Khaled', 'last_name' => 'BEN MOKDAD', 'email' => 'benmokdad.khaled@hotmail.com'),
    array('username' => 'GE369', 'first_name' => 'Mohamed', 'last_name' => 'BOUZID', 'email' => 'barguellil@bluewin.ch'),
    array('username' => 'VD1377', 'first_name' => 'José', 'last_name' => 'PALHARES', 'email' => 'zepalhares@bluewin.ch'),
    array('username' => 'GE269', 'first_name' => 'Hichem', 'last_name' => 'GATRI', 'email' => 'gatri1976@gmail.com'),
    array('username' => 'GE553', 'first_name' => 'Fadil', 'last_name' => 'TABK', 'email' => 'fadel.tabk@gmail.com'),
    array('username' => 'GE1403', 'first_name' => 'Morad', 'last_name' => 'HASNAOUI', 'email' => 'hasn@bluewin.ch'),
    array('username' => 'VD213413', 'first_name' => 'George', 'last_name' => 'BAJANARU', 'email' => 'getaxis@gmail.com'),
    array('username' => 'GE490', 'first_name' => 'Adnan', 'last_name' => 'IBRAHIM', 'email' => 'adnan.ibrahim@bluewin.ch'),
    array('username' => 'GE133', 'first_name' => 'Fernando', 'last_name' => 'MARINO', 'email' => 'nandojam@hotmail.com'),
    array('username' => 'NE1', 'first_name' => 'Yann', 'last_name' => 'VERMOT', 'email' => 'yann.vermot@gmail.com'),
    array('username' => 'GE215', 'first_name' => 'Paulo', 'last_name' => 'RIBEIRO', 'email' => 'ribeiropaulo1212@gmail.com'),
    array('username' => 'VD491034', 'first_name' => 'Papa Ibrahima', 'last_name' => 'SARR', 'email' => 'sarr614@gmail.com'),
    array('username' => 'SH36066', 'first_name' => 'Khemais', 'last_name' => 'MEJRI', 'email' => 'kmejri@bluewin.ch'),
    array('username' => 'GE1654', 'first_name' => 'Joaquim', 'last_name' => 'DE ALMEIDA', 'email' => 'dealmeidajoaquim@hotmail.com'),
    array('username' => 'GE707', 'first_name' => 'Omar', 'last_name' => 'LATIF', 'email' => 'omarcab@gmail.com'),
    array('username' => 'toto', 'first_name' => 'Axel', 'last_name' => 'Pagliotti', 'email' => 'florian@rond.ch'),
    array('username' => 'toto', 'first_name' => 'Axel', 'last_name' => 'Pagliotti', 'email' => 'maurice@perry.ch'),
);

$smarty = create_smarty(NULL);
?>
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
    </head>
    <body>
<?php
foreach ($taxis as $taxi) {
    $mail = create_mailer();
    $mail->From = MAIL_FROM;
    $mail->FromName = MAIL_FROM_NAME;
    $mail->addAddress($taxi["email"], $taxi["first_name"] . " " . $taxi["last_name"]);
    $mail->Subject = "Transformation des métiers du taxi";
    $mail->ContentType = "text/html";
    $mail->CharSet = "UTF-8";
    $mail->Body = $smarty->fetch("announcement.html");
    $mail->AltBody = $smarty->fetch("announcement.txt");
    if ($mail->send()) { ?>
        <?php echo $taxi["email"]; ?> OK<br>
<?php
    } else { ?>
        <?php echo $taxi["email"]; ?> KO<br>
<?php
    }
}
?>
    </body>
</html>
